openaiApiKey: "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"
openaiOrganizationID: "org-te44ggakSv74AWbRA5ss3wPS"
chatgptTriggerKeyword: "kay"
