openaiApiKey: "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"
openaiOrganizationID: "org-te44ggakSv74AWbRA5ss3wPS"
chatgptTriggerKeyword: "kay"
