openaiApiKey: "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"
openaiOrganizationID: "org-te44ggakSv74AWbRA5ss3wPS"
chatgptTriggerKeyword: "kay"
